export const PRODUCT_NAME = "SchemeWise AI";
export const BRAND_NAME = "Scheme Predictor";
export const BRAND_SUBTITLE = "AI-powered scheme discovery";
export const PRODUCT_TAGLINE = "Government Scheme Discovery & Eligibility Research Platform";
export const PRODUCT_SHORT =
  "Discover government schemes you may be eligible for using your socio-economic profile.";

export const RESEARCH_BADGE = "Academic Research Prototype";
export const RESEARCH_NOTICE =
  "This platform uses synthetic citizen data and documented scheme rules for research purposes. Predictions are not government approval or final eligibility decisions.";

export const STANDARD_DISCLAIMER = RESEARCH_NOTICE;

export const PROBABILITY_LABEL = "Model prediction probability";
export const PROBABILITY_EXPLANATION =
  "This probability is produced by the research model and should not be interpreted as government approval.";

export const PREDICTED_ELIGIBLE = "Predicted Eligible";
export const OFFICIAL_SOURCE = "Official Source";
export const SUPPORTED_SCHEMES = "Supported schemes";

export const NETWORK_ERROR =
  "Unable to connect to SchemeWise AI right now. Please make sure the service is running and try again.";
export const SERVER_ERROR = "Something went wrong while processing your request. Please try again.";
export const SESSION_EXPIRED = "Your session has expired. Please sign in again.";
export const VALIDATION_ERROR = "Please check the information entered and try again.";
export const ANALYZING_TITLE = "Analyzing Your Profile";
export const ANALYZING_TEXT = "Checking your information against the supported scheme rules...";

export const RESEARCH_EVALUATION_BANNER = "Synthetic Dataset • Rule-Derived Labels • CORE Schemes";

export const SYSTEM_FLOW_STEPS = [
  "Official Scheme Information",
  "Scheme Dataset",
  "Eligibility Rules",
  "Synthetic Citizen Dataset",
  "ML Training",
  "Decision Tree",
  "Rule + ML Comparison",
  "FastAPI",
  "React Portal",
  "Scheme Recommendations",
] as const;

export const WALLET_NOT_IDENTITY =
  "This wallet is a research prototype profile store. It is not a government identity system.";

export const HISTORY_TITLE = "Recommendation History";
export const HISTORY_SUBTITLE =
  "Review previous scheme checks from your socio-economic profile.";
export const HISTORY_DISCLAIMER =
  "These are previous AI research prototype results, not official government eligibility decisions.";
export const HISTORY_EMPTY_TITLE = "No recommendation history yet";
export const HISTORY_EMPTY_DESCRIPTION =
  "Complete your profile and check eligible schemes to see your previous results here.";
export const HISTORY_DELETE_TITLE = "Delete this recommendation history?";
export const HISTORY_DELETE_DETAIL =
  "This only removes the saved research result. Your wallet profile will not be deleted.";

export const COMPLETENESS_TITLE = "Profile Completeness";
export const COMPLETENESS_HINT =
  "Complete your profile to provide the most complete information for scheme recommendation.";
export const COMPLETENESS_DONE = "Your profile is complete.";
export const COMPLETENESS_MISSING = "Missing information";

export const COMPARE_TITLE = "Compare Recommended Schemes";
export const COMPARE_SUBTITLE =
  "Review up to three recommended CORE schemes side by side using official catalog information.";
export const COMPARE_HINT = "Select 2 or 3 recommended schemes to compare.";
export const COMPARE_SIGN_IN =
  "Sign in with a saved wallet to compare schemes or download a PDF report. Comparison uses your saved socio-economic profile.";
export const COMPARE_WALLET_NOTE =
  "Comparison and PDF reports use your saved wallet profile, not values typed only on the public check form.";
export const REPORT_DISCLAIMER =
  "This report is generated by an academic AI research prototype using synthetic/research data and documented scheme rules. It is not government approval, certification, or a final eligibility determination. Users should verify eligibility and application requirements with the official government source.";
export const NOT_OFFICIAL_REJECTION =
  "A scheme that is not recommended is a research prototype result, not an official government rejection.";
