"""Pydantic models for on-demand recommendation PDF reports."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.schemas.prediction import SchemeId

REPORT_DISCLAIMER = (
    "This report is generated by an academic AI research prototype using "
    "synthetic/research data and documented scheme rules. It is not government "
    "approval, certification, or a final eligibility determination. Users should "
    "verify eligibility and application requirements with the official government source."
)

PROJECT_TITLE = (
    "State Government Sponsored Scheme Eligibility Predictor Engine "
    "Utilizing Unified Socio-Economic Data Wallets"
)


class RecommendationReportRequest(BaseModel):
    compare_scheme_ids: list[SchemeId] = Field(default_factory=list, max_length=3)
    language: Literal["en", "ta"] = "en"

    @field_validator("compare_scheme_ids")
    @classmethod
    def valid_optional_comparison(cls, value: list[SchemeId]) -> list[SchemeId]:
        if not value:
            return value
        if len(value) < 2:
            raise ValueError("Compare 2 or 3 unique CORE scheme IDs, or omit comparison.")
        if len(set(value)) != len(value):
            raise ValueError("Scheme IDs must be unique.")
        return value

    model_config = ConfigDict(
        json_schema_extra={"example": {"compare_scheme_ids": [], "language": "en"}}
    )
